### ISSUE TITLE
XYGrid wrong rounding

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#146]
**Describe the bug**
we talked about it, please fix!!!

**Comment by tyrasd** [comment]
OK. At second thought I believe this isn't actually an issue. Because you were requiring the coordinates in the bounding box object to be stored in higher precision than what we support in the OSHDB. OSM data only provides latitude/longitude values of 7 decimal digits, so the OSHDB also limits itself to the same amount of precisions.
This allows for some optimizations that would otherwise not be possible, for example the ability to store coordinates in integer variables (after a normalization). This is for example done in the OSHDBBoundingBox class. Naturally, when one tries to store coordinates of even higher precision in such objects, the result will be rounded or truncated at some point and produce potentially unexpected results.

But I believe as long as these classes are used in their expected regime of operation, they work as expected. Let's reopen this issue if we find a concrete bug caused by this. :wink:

**Comment by tyrasd** [comment]
see also #78
