### ISSUE TITLE
OSMContribution.getContibutorUserId() returns 0 on deletion

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/oshdb#150]
**Describe the bug**
The method `.getContributorUserId()`of the `OSMContribution` returns 0 if the contribution is a deletion. This is because the uid of a deleted object is stored as 0 and the method looks at the entity after the contribution. 

**To Reproduce**
OSHDB-Api-code:
  ```  
Set<Integer> user = OSMContributionView.on(oshdb)
        .osmType(EnumSet.of(OSMType.NODE))
        .areaOfInterest(new OSHDBBoundingBox(11.231477,45.995781,11.378763,46.070384))
        .filter(contrib -> contrib.getEntityAfter().getId()==3714798059L)
        .timestamps("2015-10-17","2018-10-18")
        .map(contrib -> contrib.getContributorUserId())
        .uniq();
    
    System.out.println(user);
    oshdb.close();
```

returns 0

https://www.openstreetmap.org/node/3714798053/history

**Expected behavior**
The result should be 13591 (https://www.openstreetmap.org/user/lucadelu)

**System:**
 - OS: . Ubuntu 18.04
 - Java Version: openjdk version "1.8.0_191"
 - OSHDB Version 0.5.0-SNAPSHOT
 - Maven version 3.3.2

**Comment by tyrasd** [comment]
I could have sworn that we had reported (and fixed) this issue already, but can't find anything right now. :confused: hmm, maybe I was thinking about https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb/issues/114...

> This is because the uid of a deleted object is stored as 0

This seems like an error in the OSHDB import routine. Since OSM entities have uids also if the version is marked as deleted (`visible=false`).

**Comment by SlowMo24** [comment]
so this needs a deep fix in the oshdb-core, right @rtroilo ?

**Comment by SlowMo24** [comment]
- [ ] needs test-data in ETL to write unit-test!

**Comment by rtroilo** [comment]
many thanks to @SlowMo24, this issue is solved now.
