### ISSUE TITLE
rename packages to match updated groupId

### ISSUE THREAD

**Issue by joker234** [GIScience/oshdb#241]
Open TODOs from #234:
See [comment](https://github.com/GIScience/oshdb/pull/234#pullrequestreview-407701110).

- Move sources `src/main/java/org/heigit/bigspatialdata` → `src/main/java/org/heigit/ohsome`
- Move tests `src/test/java/org/heigit/bigspatialdata` → `src/test/java/org/heigit/ohsome`
- Rename imports
- Better use `grep` and `find` after these changes again, if I missed anything.

**Comment by joker234** [comment]
Don't forget to fix [oshdb-examples#1](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb-examples/issues/1) when this is fixed.

**Comment by tyrasd** [comment]
In principle all dependent repositories need to be updated (ohsome-api, ohsome-filter, oshdb-benchmarks, etc.)

**Comment by tyrasd** [comment]
postponed to 0.7, because 

1. it would have made any "0.5" H2 files incompatible (which work otherwise still fine with 0.6)
2. upgrading the ohsome-filter library would have been difficult. -> will be solved by integrating into this repository (see https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/libs/ohsome-filter/-/issues/15)
