### ISSUE TITLE
How to generate OSHDB data extracts?

### ISSUE THREAD

**Issue by Guiming** [GIScience/oshdb#330]
I'd like to run queries on the most recent OSM history dump. How can I generate OSHDB data extracts myself, instead of downloading from the download server at https://downloads.ohsome.org/v0.6/? 

Data extracts on the download server are dated as August 2020.

Thanks in advance.

**Comment by rtroilo** [comment]
Hello @Guiming and Happy New New,

you find the documentation how to generating OSHDB extracts here:

- https://github.com/GIScience/oshdb/tree/master/oshdb-tool/etl

The current implementation is quite resource intensive and we are going to publish a new way to generate a OSHDB extract, probably mid of January, which solves this problem.

In the meanwhile I'm happy to provide you with a most recent OSHDB extract, just let me know your regions of interest.

Do you also know our web api for executing common queries on OSM history data, https://api.ohsome.org?

**Comment by Guiming** [comment]
Thank you for the pointers. They are helpful.
I am interested in US and China. Could you provide me a link to download the latest OSHDB extracts for these two countries?

**Comment by rtroilo** [comment]
Hi @Guiming,

you are welcome!

I just uploaded your requested full history OSHDB extracts US and China:
- https://downloads.ohsome.org/v0.6/north-america/us_2021-01-06.oshdb.mv.db (50GB)
- https://downloads.ohsome.org/v0.6/asia/china_2021-01-06.oshdb.mv.db (4.8GB)

I took the source for your extracts from geofabrik, downloaded on 2021-01-06!
- https://download.geofabrik.de/north-america/us.html  (us-internal.osh.pbf)
- https://osm-internal.download.geofabrik.de/asia/china.html (china-internal.osh.pbf)


Let us now if you got any question or if we can support you with your OSHDB queries.

Looking forward to hear from you.

**Comment by Guiming** [comment]
Thank you very much!

**Comment by Guiming** [comment]
A follow-up question regarding oshdb data extracts.

There are two .oshdb.mv.db files in the root-level folder on the [download server](https://downloads.ohsome.org/v0.6/):

1. planet_2021-01-30T0300Z_grid.oshdb.mv.db. I assume this is the H2 database file containing OSM history for the whole world. But its name has "_grid" in it. Is this file somewhat different from other H2 database files (e.g., compared to north-america/us_2021-01-06.oshdb.mv.db)?

2. planet_2021-01-30T0300Z_keytables.oshdb.mv.db. What is this database file for? Is this file needed along with file 1 to run OSHDB queries/aggregations?

I have run queries/aggregations using north-america/us_2021-01-06.oshdb.mv.db without needing a "*keytables.oshdb.mv.db" file. Any clarification would be greatly appreciated.
Thank you.

**Comment by rtroilo** [comment]
Hi @Guiming ,

yes you are right, and sorry for the confusion.
the  us_2021-01-06 and china_2021-01-06, both have the keytables included. 
for the current planet_2021-01-30 files the keytables is separat.

In order to use the current planet_2021-01-30 you need the specify the right keytable for the view.

```java
try (var oshdb = new OSHDBH2("planet_2021-01-30T0300Z_grid.oshdb");
     var keytables = new OSHDBH2("planet_2021-01-30T0300Z_keytables.oshdb");){
     oshdb.multithreading(true); //optional
     OSMContributionView.on(oshd).keytables(keytables)
     ...
}
```
At the moment  keytables are not interchangeable, because of the way we optimize the mapping between textual key/value and id base key/values.

So when you see on our download server a separate keytable "..._keytable.oshdb" than you have to use it in combination with the "..._grid.oshdb". 
Be aware that you get a warning by using planet_.._grid.oshdb.mv.db without a separate keytable, BUT you don't get a warning when you, for example, use us_2021-01-06 with the planet_2021-01-30_keytable!

Thank you for pointing this out. I will write a readme for our the download site.

**Comment by rtroilo** [comment]
Just to clarify. In order to keep our dataset compact, we use id-base key/value/roles references in our oshdb (grid).
To translate between id-base to string base,  we keep the textual references in the oshdb keytables.
This are just 3 tables + 1 for metadata with
- keys (id int,txt text) -- keyid to keytxt 
- keyvalues (keyid int, valueid int, txt text) -- tag to value txt
- roles (id int, txt text) -- roles for relation member
- metadata (key,value) -- properties

You can have a look inside the keytables h2 database, to see this tables.
Internally we store for example 'highway'='primary' as 2,9.

```sql
select k.txt, kv.txt from keyvalue kv join key k on keyid = k.id
where keyid = 2 and valueid = 9
-- 'highway', 'primary'
```
or the other way around.

```sql
select keyid, valueid, k.txt, kv.txt from key k join keyvalue kv on keyid = k.id 
where k.txt = 'highway' and kv.txt = 'primary'
-- 2, 9, 'highway', 'primary'
```

**Comment by Guiming** [comment]
@rtroilo, Thanks for the clarification!

I tried testing out effects of the keytables, and I got different results when using or not using the keytables. I wonder why they are different. Which result is supposed to be correct? You mentioned that keytables are not interchangeable, and china_2021-01-06.oshdb.mv.db has keytables included already. So my guess is that the result from using the separate keytables (planet_2021-01-30T0300Z_keytables.oshdb.mv.db) is incorrect as the two .db files do not *match* (so using the mismatched keytables mess up things). Is that right?

Also, there are tons of warnings ("... unable to find tag ...") when not using the keytables. Why is it so, given that keytables are included in china_2021-01-06.oshdb.mv.db already?

Inputs:

`var oshdb = new OSHDBH2("china_2021-01-06.oshdb.mv.db");
var keytables = new OSHDBH2("planet_2021-01-30T0300Z_keytables.oshdb.mv.db");
oshdb.multithreading(true);`

Running the following code prints **119553.18455581245** [using keytables;  no warnings] 

`Number result = OSMEntitySnapshotView.on(oshdb).keytables(keytables)
	        .areaOfInterest(new OSHDBBoundingBox(116,39.6,117,40.3))
	        .timestamps("2019-01-01")
	        .osmType(OSMType.WAY)
	        .osmTag("building")
	        .map(snapshot -> Geo.areaOf(snapshot.getGeometry()))
	        .filter(area -> area < 1000.0)
	        .sum();
	    System.out.println(result);`

Running the following code prints **1.7955073749326896E7** [not using keytables; tons of warnings "unable to find tag ..."] 

`Number result = OSMEntitySnapshotView.on(oshdb)
	        .areaOfInterest(new OSHDBBoundingBox(116,39.6,117,40.3))
	        .timestamps("2019-01-01")
	        .osmType(OSMType.WAY)
	        .osmTag("building")
	        .map(snapshot -> Geo.areaOf(snapshot.getGeometry()))
	        .filter(area -> area < 1000.0)
	        .sum();
	    System.out.println(result);`

**Comment by rtroilo** [comment]
Hi @Guiming,

thank you that you are asking.

>  You mentioned that keytables are not interchangeable, and china_2021-01-06.oshdb.mv.db has keytables included already. So my guess is that the result from using the separate keytables (planet_2021-01-30T0300Z_keytables.oshdb.mv.db) is incorrect as the two .db files do not match (so using the mismatched keytables mess up things). Is that right?

yes that's right!

> I wonder why they are different.

In the moment of the import from pbf to oshdb, we build up a statistic of how often a key and key/value combination is used, based on that we assign global  ids. A lower id of a key indicates, that this key appears more often in the dataset.
```sql
select id, txt from key limit 3;
-- 0 "building"
-- 1 "source"
-- 2 "highway"
```
In this case the key = 'building' is the most used key in the dataset and for the key='building', 'yes' is the most used value.
```sql
select keyid, valueid, txt from keyvalue where keyid = 0 limit 3;
-- 0 0 "yes"
-- 0 1 "house"
-- 0 2 "residential"
```
Internally we use [varint ](https://developers.google.com/protocol-buffers/docs/encoding#varints)encoding to the key/value ids for each osm-entity, lower ids result in less space usage, and so the most often key and key/value combination used the least amount of space.

It is obvious that for different datasets/extract, you get different statistics and so different textural to id mapping.

> Also, there are tons of warnings ("... unable to find tag ...") when not using the keytables. Why is it so, given that keytables are included in china_2021-01-06.oshdb.mv.db already?

In order to correctly build a geometry for an osm-way/osm-relation, it is relevant to interpret the tags for that entity.
For example, an osm-way tagged with 'highway'='yes' results in a line-string, while tagged with 'building'='yes' in a polygon.
To see a full list of key/value combination which results in a polygon see:
https://github.com/GIScience/oshdb/blob/master/oshdb-util/src/main/resources/json/polygon-features.json
You can overwrite the defaults, by using your own logic by implementing the  [TagInterpreter](https://github.com/GIScience/oshdb/blob/master/oshdb-util/src/main/java/org/heigit/ohsome/oshdb/util/taginterpreter/TagInterpreter.java) interface.
```java
TagInterpreter tt = new MyOwnTagInterpreter();
OSMEntitySnapshotView.on(oshdb)
  .tagInterpreter(tt)
  ...
```
The warnings you get should only occur for an extract, because it is possible that not every key/value combination which defines a polygon-features, is found in the extract. The full-planet extract, obvious, contains all combination, so that you don't see a warning there.

About your results:
If you check the key id mapping for the china extract you see that the id for 'building' is not 0 but 3. Apparently in the china extract, 'highway' is the most used key.
```sql
select id, txt from key limit 10;
-- 0 "highway"
-- 1 "name"
-- 2 "source"
-- 3 "building"
```
The result is, that when you use the planet_keytable for the china extract, 'building' -> 0, but internally 0->'highway' you filter an the wrong elements, also the tag-to-polygon is screwed, which should also result in a lot of warnings for non-closed polygons and more!

Hope that explains the different results!
I'm very happy to explain you more on the internal work, and to help you to write/support your analysis, so don't hesitate to write me directly rafael.troilo@heigit.org, or info@heigit.org, or over github via issues.
