### ISSUE TITLE
[oshdb-filter] Question: can these be achieved using `filters` ?

### ISSUE THREAD

**Issue by y26805** [GIScience/oshdb#460]
### Problem Description
Hi, I am working on a project that leverages OSHDB and I was wondering if the following conditions can be calculated using `oshdb-filter` functionality. (Currently I am guessing no, but I would also welcome any idea to make this work)

1. Calculate the max distance between two lines (e.g. return length of residential roads situated within `x` meters of a motorway)
2. Calculate length of roads in an area with a certain key-value (e.g. return length of roads inside parks in a given city)3. 

I looked through the current docs but couldn't find any existing operators/arguments that seem to fit my needs (some kind of expressions like an `in {area}` or `distance:[...]`?) 
Would love to know if I missed something or if there's any sort of workaround for these kinds of calculations.

Thanks in advance!

### Expected Solution
Ideas where I can achieve the above using existing `oshdb-filters`

### Alternative Solutions
Extract all data that fits the description, then do my own filtering..?

**Comment by tyrasd** [comment]
The oshdb does currently support spatial joins, which would be required to calculate distance between object or spatial relations such as feature-within-feature operations. The main reason why it is not yet supported in the OSHDB is mostly due to the combination of the complexities introduced by a) dealing with historic OSM data and b) the distributed nature of the calculations performed by the OSHDB.

Depending on what you are trying to do exactly, it might be possible to implement it "client" side in your OSHDB app (e.g. first query and extract all park geometries, then use these geometries as the `areaOfInterest` (or custom [`filter`](https://github.com/GIScience/oshdb/blob/0.7.2/documentation/manual/filters.md)) in a second pass of querying; or similarly to first query all motorways, construct a buffer area around the features and use that geometry in the final query), or use traditional GIS software to perform this kind of operation.

(PS: link to related issue #106)
